[versions]
spring-boot = "3.1.2"
spring-boot-dependencies = "3.1.2"
spring-boot-starter-web = "3.1.2"
spring-boot-starter-data-jpa = "3.1.2"
spring-boot-starter-test = "3.1.2"
spring-boot-starter-security = "3.1.2"

# Java version (optional)
java = "17"

[libraries]
# Spring Boot core dependencies
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot-starter-data-jpa" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot-starter-test" }

# Additional Spring Boot dependencies
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "spring-boot-dependencies" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
