[versions]
spring-boot = "3.1.2"
kotlin = "2.0.20"
spring-dependency-management = "1.1.0"

[libraries]
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web"}
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter"}
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa"}
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security"}
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test"}
h2 = { group = "com.h2database", name = "h2", version = "2.1.214" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
