CREATE TABLE pokemon (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR NOT NULL DEFAULT '',
  HEIGHT_IN_CM NUMERIC NOT NULL DEFAULT 0,
  WEIGHT_IN_KG DOUBLE PRECISION NOT NULL DEFAULT 0,
  OWNER VARCHAR(256) NOT NULL
);
